basicapp/urls.py
from django.urls import re_path
from . import views

app_name = 'basicapp'
urlpatterns = [
    re_path(r'^other/', views.other, name='other'),
    re_path(r'^relative/', views.relative, name='relative')

]

learningtemp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basicapp import views, urls
urlpatterns = [
    path('basicapp/', include(urls)),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')

]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'basicapp/index.html')


def other(request):
    return render(request, 'basicapp/other.html')


def relative(request):
    return render(request, 'basicapp/relative_url.html')

templates/basicapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    <h1>Welcome to index</h1>
  </body>
</html>

templates/basicapp/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Other</title>
  </head>
  <body>
    <h1>Welcome to other </h1>
  </body>
</html>

templates/basicapp/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative URL</title>
  </head>
  <body>
    <h1>Welcome to relative url</h1>
    <h4>To jump to the other page please <a href={% url 'basicapp:other' %}>Click here</a> </h4>
    <a href="{% url 'admin:index' %}">Admin</a>
  </body>
</html>